---
# Ansible playbook to install software on your mac in one go!
- hosts: localhost
  connection: local

  vars:
    - homedir: "{{ lookup('env','HOME') }}"

  vars_files:
    - vars/main.yml
    - vars/settings.yml

  roles:
    - geerlingguy.homebrew


  tasks:
# Enable these in your own fork.
   - include: tasks/npm.yml
#    - include: tasks/security.yml
#    - include: tasks/defaults.yml
#    - include: tasks/network.yml

